language: node_js
sudo: false
cache:
  directories:
  - node_modules
node_js:
- 12
script: npm run lint && npm run test:travis
deploy:
  skip_cleanup: true
  provider: npm
  email: chris@cvbytes.com
  api_key:
    secure: NumvwlEYKB45r62impI4m3DSswegggrqWB9mLgwqfOYL+5IQkbOhX4q/ZVO9Qkky6p5sU1MZYZR68OLJ69WgfWVmWUm6qx1Brp7iiwTRipgA8SO+umdKZtewNN58rRF44VeHMw6fq0495YYk/oMuXyrI7eyFfeIjMVQXRbsA8unTVJpKtjeOnuCW1ZNrQfdACa25GB+aS2vgFx7g0JGdvCRyZ4+P/E7+uw4YwzwyLI3yjO2CxmGw45rq1F7F9n8t1k70aJEpfNKirI4+MEP74RK4hNh7BEjIVkUSh6+pbVpc8DpdcVS9Js/QaiSTbhec54rvxhVprn2ojTJscWlXTF39qwX519q9nHttXf6h0TcwZoi7ZRcJztbUYCmYwN+PsGjfm31qDWwA8qbyp+8Hy5+0/3OFRaL6izNb1ylrnS6RVzI7+aNpL/6/N8/eABUQSOs9jwg/gxg98HlLr4kbG3M9VRYfthOtXeg4UzLusV75nXwWCCLvTRPlPwqg2JAsRM9cBSO7Grrq18wMTeM4ZXm8fLTA5u0NaFpHXgFT8lGgsiwm9a1GvkrL2x/SGx5S+zr0Gp9WZo9aOB26AlfknVc4SASLJ1GfAEgJTd0MADDTCBj5nkUyfe8ea/HkTus4N6UIZPSoCgLqX3yfBWRg4rySqPTfYgLM/rN9XJt6Q7A=
  on:
    repo: seevee/vue-d3-axis
    branch: master
